server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://119.3.221.141:3306/alioss?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Aabc123456789

